export const DEFAULT_DIVISION_POINT_SIZE = 20;
export const DEFAULT_SWITCH_COLOR = '#666';
export const DEFAULT_DIVISION_COLOR = '#bbb';
export const DEFAULT_BORDER_SIZE = 5;
export const DEFAULT_DIVISION_LINE_HEIGHT = 5;
export const DEFAULT_SCALE_WHILE_DRAG = 1.2;
